name: Docker Build CI

on:
  push:
    branches: [ "stage/build-v1" ]
  pull_request:
    branches: [ "stage/build-v1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Build Docker image for linux/amd64
        run: docker buildx build --file Dockerfile --platform linux/amd64 -t fire-webapp-amd64:v1 .
      
      - name: Build Docker image for linux/arm64
        run: docker buildx build --file Dockerfile --platform linux/arm64 -t fire-webapp-arm64:v1 .


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Clone ECR Templates Repo
        run: git clone --branch stage/ECR_templates https://github.com/yuvaraja402/AWS_Infrastructure_Templates.git

      - name: Setup Terraform Directory
        working-directory: ./AWS_Infrastructure_Templates/ECR
        run: |
          terraform init
          terraform plan \
            -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="ecr_repo_name=fire-webapp-repo" \
            -var="ecr_region=eu-west-1"