name: Docker Build CI

on:
  push:
    branches: [ "stage/build-v1" ]
  pull_request:
    branches: [ "stage/build-v1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for linux/amd64
        run: |
        docker buildx create --use
        docker buildx build --file Dockerfile --platform linux/amd64 -t fire-webapp-amd64:v1 .